export enum GraphItemTypes {
    sword = 'sword',
    chess = 'receipt',
    bankbook = 'bankbook',
    strateg = 'strategyy',
    onlinebanking = 'onlinebanking',
    timer1 = 'atm',
    money = 'money',
    smartphonepayment = 'smartphone-payment',
    horse = 'cloudbanking',
    portfolio = 'portfolio',
    banking = 'banking',
    smartphone = 'smartphone',
    timer = 'smartphone1',
    bankaccount1 = 'bankaccount1',
    bankaccount = 'bankaccount',
    borrow = 'borrow',
    queen1 = 'queen1',
    strategy = 'credit-card',
    swimlane = 'swimlane',
    rectangle = 'rectangle',
    rounded = 'rounded',
    ellipse = 'ellipse',
    rhombus = 'rhombus',
    triangle = 'triangle',
    cylinder = 'cylinder',
    actor = 'actor'
}
