export enum GraphItemTypes {
    sword = 'sword',
    chess = 'chess',
    trophy = 'trophy',
    strateg = 'strategyy',
    horseriding = 'horseriding',
    timer1 = 'timer1',
    rook = 'rook',
    queen = 'queen',
    horse = 'horse',
    bishop = 'bishop',
    pawn = 'pawn',
    king = 'king',
    timer = 'timer',
    chessboard = 'chessboard',
    chessboard1 = 'chessboard1',
    crown1 = 'crown1',
    queen1 = 'queen1',
    strategy = 'strategy'
}
