export enum IconPaths {
    trophy= '../assets/icons/svg/001-trophy.svg',
    timer1= '../assets/icons/svg/002-timer-1.svg',
    sword= '../assets/icons/svg/003-sword.svg',
    chess= '../assets/icons/svg/004-chess.svg',
    strategy= '../assets/icons/svg/005-strategy.svg',
    rook= '../assets/icons/svg/006-rook.svg',
    queen= '../assets/icons/svg/007-queen.svg',
    pawn= '../assets/icons/svg/008-pawn.svg',
    king = '../assets/icons/svg/009-king.svg',
    horse= '../assets/icons/svg/010-horse.svg',
    crown1= '../assets/icons/svg/011-crown-1.svg',
    crown= '../assets/icons/svg/012-crown.svg',
    timer= '../assets/icons/svg/013-timer.svg',
    chessboard1= '../assets/icons/svg/014-board-1.svg',
    chessboard= '../assets/icons/svg/015-board.svg',
    bishop = '../assets/icons/svg/016-bishop.svg',
    horseriding = '../assets/icons/svg/017-riding.svg',
    zoomOut = '../assets/icons/svg/AM_Flow_Icons_ZoomOut.svg',
    zoomIn = '../assets/icons/svg/AM_Flow_Icons_ZoomIn.svg',
    fit = '../assets/icons/svg/AM_Flow_Icons_Fit.svg',
    actual = '../assets/icons/svg/AM_Flow_Icons_Actual.svg',
}
